services:
  csgo-skins-bot:
    build: .
    container_name: csgo-skins-bot
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
      - PYTHONUNBUFFERED=1
      - PROXY_IP_PORT=${PROXY_IP_PORT}
