services:
  csgo-skins-bot:
    build: .
    container_name: csgo-skins-bot
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
      - PROXY_HOST_IP=${PROXY_HOST_IP}
      - PYTHONUNBUFFERED=1
